all: nasteroids-seq.cpp
	g++ -std=c++14 nasteroids-seq.cpp -Wall -Wextra -Wno-deprecated -Werror -pedantic -pedantic-errors -o salida-seq.out  

clean:
	$(RM) salida-seq.out
	$(RM) init_conf.txt
	$(RM) out.txt
